#!/usr/bin/env php
<?php

declare(strict_types=1);

$command = $argv[1] ?? 'help';

if ($command === 'serve') {
    $host = '127.0.0.1';
    $port = '8000';

    foreach ($argv as $arg) {
        if (str_starts_with($arg, '--host=')) {
            $host = substr($arg, 7);
        }
        if (str_starts_with($arg, '--port=')) {
            $port = substr($arg, 7);
        }
    }

    fwrite(STDOUT, "Starting development server: http://{$host}:{$port}\n");
    passthru(sprintf('php -S %s:%s -t public', escapeshellarg($host), escapeshellarg($port)), $exitCode);
    exit($exitCode);
}

if ($command === 'help' || $command === '--help' || $command === '-h') {
    fwrite(STDOUT, "Audit Management System CLI\n\n");
    fwrite(STDOUT, "Supported commands:\n");
    fwrite(STDOUT, "  serve [--host=127.0.0.1] [--port=8000]   Start local dev server\n");
    exit(0);
}

fwrite(STDERR, "Command '{$command}' is not available in this lightweight scaffold.\n");
fwrite(STDERR, "Use 'php artisan serve' or 'php artisan help'.\n");
exit(1);
