CREATE TABLE roles (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50) NOT NULL UNIQUE
);

CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(100) NOT NULL UNIQUE,
    email VARCHAR2(150) NOT NULL UNIQUE,
    password VARCHAR2(255) NOT NULL,
    created_by VARCHAR2(100) NOT NULL,
    created_date TIMESTAMP NOT NULL,
    updated_by VARCHAR2(100),
    updated_date TIMESTAMP,
    deleted NUMBER(1) DEFAULT 0 NOT NULL
);

CREATE TABLE user_roles (
    user_id NUMBER NOT NULL,
    role_id NUMBER NOT NULL,
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES roles(id),
    CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role_id)
);

CREATE TABLE audit_plan (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    audit_year NUMBER NOT NULL,
    audit_universe VARCHAR2(255) NOT NULL,
    risk_rating VARCHAR2(20) NOT NULL,
    assigned_auditor_id NUMBER NOT NULL,
    created_by VARCHAR2(100) NOT NULL,
    created_date TIMESTAMP NOT NULL,
    updated_by VARCHAR2(100),
    updated_date TIMESTAMP,
    deleted NUMBER(1) DEFAULT 0 NOT NULL,
    CONSTRAINT fk_plan_user FOREIGN KEY (assigned_auditor_id) REFERENCES users(id)
);

CREATE TABLE audit_engagement (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(255) NOT NULL,
    audit_plan_id NUMBER NOT NULL,
    working_paper_url VARCHAR2(500),
    created_by VARCHAR2(100) NOT NULL,
    created_date TIMESTAMP NOT NULL,
    updated_by VARCHAR2(100),
    updated_date TIMESTAMP,
    deleted NUMBER(1) DEFAULT 0 NOT NULL,
    CONSTRAINT fk_engagement_plan FOREIGN KEY (audit_plan_id) REFERENCES audit_plan(id)
);

CREATE TABLE finding (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    engagement_id NUMBER NOT NULL,
    risk_rating VARCHAR2(20) NOT NULL,
    observation CLOB NOT NULL,
    root_cause CLOB,
    recommendation CLOB,
    management_response CLOB,
    target_completion_date DATE,
    status VARCHAR2(20) NOT NULL,
    created_by VARCHAR2(100) NOT NULL,
    created_date TIMESTAMP NOT NULL,
    updated_by VARCHAR2(100),
    updated_date TIMESTAMP,
    deleted NUMBER(1) DEFAULT 0 NOT NULL,
    CONSTRAINT fk_finding_engagement FOREIGN KEY (engagement_id) REFERENCES audit_engagement(id)
);

CREATE TABLE action_plan (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    finding_id NUMBER NOT NULL,
    remediation_action CLOB NOT NULL,
    evidence_url VARCHAR2(500),
    created_by VARCHAR2(100) NOT NULL,
    created_date TIMESTAMP NOT NULL,
    updated_by VARCHAR2(100),
    updated_date TIMESTAMP,
    deleted NUMBER(1) DEFAULT 0 NOT NULL,
    CONSTRAINT fk_action_finding FOREIGN KEY (finding_id) REFERENCES finding(id)
);

-- Optional: create read-only reporting user for Oracle report endpoints.
-- CREATE USER audit_report_reader IDENTIFIED BY audit_report_reader;
-- GRANT CREATE SESSION TO audit_report_reader;
-- GRANT SELECT ON users TO audit_report_reader;
-- GRANT SELECT ON audit_plan TO audit_report_reader;
-- GRANT SELECT ON audit_engagement TO audit_report_reader;
-- GRANT SELECT ON finding TO audit_report_reader;
-- GRANT SELECT ON action_plan TO audit_report_reader;
